### ISSUE TITLE
Error reading the remote package.json file (connect UNKOWN 185.199.108.133:443 - Local (undefined: undefined))

### ISSUE THREAD

**Issue by ghost** [vingard/Tactical-Intervention-Revived#25]
Running the launcher with wine or proton results in this:
![image](https://github.com/vingard/Tactical-Intervention-Revived/assets/43009301/88adca53-9e03-48ae-9ce3-86a0ca1e8fa8)

I tried installing in a virtual machine and transferring it, but it still threw me this error. No idea what it means.

**Comment by vingard** [comment]
Linux is not supported
